from geoalchemy2 import Geometry
from sqlalchemy import Column, DateTime, Float, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Era5(Base):
    __tablename__ = 'era5'
    time = Column(DateTime)
    u10_min = Column(Float)
    u10_max = Column(Float)
    u10_mean = Column(Float)
    v10_min = Column(Float)
    v10_max = Column(Float)
    v10_mean = Column(Float)
    d2m_min = Column(Float)
    d2m_max = Column(Float)
    d2m_mean = Column(Float)
    t2m_min = Column(Float)
    t2m_max = Column(Float)
    t2m_mean = Column(Float)
    lai_hv_min = Column(Float)
    lai_hv_max = Column(Float)
    lai_hv_mean = Column(Float)
    pev_min = Column(Float)
    pev_max = Column(Float)
    pev_mean = Column(Float)
    slhf_min = Column(Float)
    slhf_max = Column(Float)
    slhf_mean = Column(Float)
    ssr_min = Column(Float)
    ssr_max = Column(Float)
    ssr_mean = Column(Float)
    str_min = Column(Float)
    str_max = Column(Float)
    str_mean = Column(Float)
    ssh_min = Column(Float)
    ssh_max = Column(Float)
    ssh_mean = Column(Float)
    e_min = Column(Float)
    e_max = Column(Float)
    e_mean = Column(Float)
    tp_min = Column(Float)
    tp_max = Column(Float)
    tp_mean = Column(Float)
    geom = Column(Geometry('POINT'))