from geoalchemy2 import Geometry
from sqlalchemy import Column, DateTime, Float, MetaData, Table

era5_table = Table(
    "era5",
    MetaData(),
    Column("time", DateTime),
    Column("u10_min", Float),
    Column("u10_max", Float),
    Column("u10_mean", Float),
    Column("v10_min", Float),
    Column("v10_max", Float),
    Column("v10_mean", Float),
    Column("d2m_min", Float),
    Column("d2m_max", Float),
    Column("d2m_mean", Float),
    Column("t2m_min", Float),
    Column("t2m_max", Float),
    Column("t2m_mean", Float),
    Column("lai_hv_min", Float),
    Column("lai_hv_max", Float),
    Column("lai_hv_mean", Float),
    Column("pev_min", Float),
    Column("pev_max", Float),
    Column("pev_mean", Float),
    Column("slhf_min", Float),
    Column("slhf_max", Float),
    Column("slhf_mean", Float),
    Column("ssr_min", Float),
    Column("ssr_max", Float),
    Column("ssr_mean", Float),
    Column("str_min", Float),
    Column("str_max", Float),
    Column("str_mean", Float),
    Column("ssh_min", Float),
    Column("ssh_max", Float),
    Column("ssh_mean", Float),
    Column("e_min", Float),
    Column("e_max", Float),
    Column("e_mean", Float),
    Column("tp_min", Float),
    Column("tp_max", Float),
    Column("tp_mean", Float),
    Column("geometry", Geometry("POINT")),
)
